name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'chatvedaai' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  GCP_SERVICE_ACCOUNT: chatveda-app@chatvedaai.iam.gserviceaccount.com

  FRONTEND_SERVICE: 'frontend-service' # Cloud Run Service Name for Frontend
  BACKEND_SERVICE: 'backend-service' # Cloud Run Service Name for Backend
  ARTIFACT_REPO: 'chatvedaai-repo' # Name of Artifact Registry repository

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Authenticate Docker with Google Artifact Registry
      - name: 'Docker Auth'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build and Push Backend Image
      - name: 'Build and Push Backend Image'
        run: |
          BACKEND_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/backend:${{ github.sha }}"
          echo "Building Backend Image: ${BACKEND_TAG}"
          docker build -t "${BACKEND_TAG}" -f backend/Dockerfile .
          docker push "${BACKEND_TAG}"

      # Build and Push Frontend Image
      - name: 'Build and Push Frontend Image'
        run: |
          FRONTEND_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/frontend:${{ github.sha }}"
          echo "Building Frontend Image: ${FRONTEND_TAG}"
          docker build -t "${FRONTEND_TAG}" -f frontend/Dockerfile .
          docker push "${FRONTEND_TAG}"

      # Deploy Backend to Cloud Run
      - name: 'Deploy Backend to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.BACKEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/backend:${{ github.sha }}'

      # Deploy Frontend to Cloud Run
      - name: 'Deploy Frontend to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.FRONTEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/frontend:${{ github.sha }}'

      # Show Deployment URLs
      - name: 'Show Cloud Run URLs'
        run: |
          echo "Backend Service URL: ${{ steps.deploy-backend.outputs.url }}"
          echo "Frontend Service URL: ${{ steps.deploy-frontend.outputs.url }}"
